axis_linear: 1
scale_linear: 0.2
scale_linear_turbo: 0.3

axis_angular: 0
scale_angular: 0.5
scale_angular_turbo: 0.8
enable_button: 8  # L2 shoulder button
enable_turbo_button: 10  # L1 shoulder button
